spring:
  config:
    activate:
      on-profile: stdio
  application:
    name: leemcp

  ai:
    mcp:
      server:
        stdio: true
        name: lee-mcp-server
        version: 1.0.0
        type: SYNC

  main:
    banner-mode: off
    web-application-type: none

logging:
  pattern:
    console: " "
  file:
    name: ./target/leemcp-logs.txt
