spring:
  application:
    name: leemcp
  config:
    activate:
      on-profile: default

  ai:
    mcp:
      server:
        enabled: true
        stdio: false
        name: lee-mcp-server
        version: 1.0.0
        type: SYNC
        sse-endpoint: /mcp
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

  main:
    banner-mode: off

logging:
  file:
    name: ./target/leemcp-logs.txt
